[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
vault = "8QR5DCLGkiNbQD5iWZXNmoUSj31ZW1Znnfw5VmX8z4WB"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/judd/wallet-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
